### ISSUE TITLE
Support functional updates for derived atoms

### ISSUE THREAD

**Issue by dwelle** [react-spring/jotai#37] opened 2020-09-13 08:29 UTC
Currently, setters of derived atoms do not support functional updates.

Proposed API:

```js
const listAtom = atom([]);
const sortedListAtom = atom((get) => get(listAtom), (_get, set, update) => set(listAtom, update));

const App = () => {
	const [list, setList] = useAtom(sortedListAtom);
	return <button onClick={() => setList((prev) => [...prev, "oi!"])}>add</button>
};
```

In other words, is there a reason why the setter of derived atom isn't a `SetStateAction` same as for primitive atoms?

**Comment by dwelle** [comment] 2020-09-13 08:41
Users can of course add it themselves:

```
const listAtom = atom([]);
const sortedListAtom = atom<List, List | (prev: List) => List>(
  (get) => get(listAtom),
  (get, set, update) => {
    return set(listAtom, typeof listAtom == "function" ? update(get(listAtom)) : update);
  }
);
```

But supporting it by default would be best.

**Comment by dai-shi** [comment] 2020-09-13 08:45
Hi @dwelle 😄 

Actually, there were that logic in Provider previously.
I removed it from the core because it's sometimes extra work, and it seems to me a hidden implication.

So, the current suggestion is:
```js
const sortedListAtom = atom(
  (get) => get(listAtom),
  (_get, set, update) => set(listAtom, typeof update === 'function' ? update(get(listAtom)) : update)
);
```

...as you commented.

**Comment by dai-shi** [comment] 2020-09-13 08:47
> But supporting it by default would be best.

We could support it with `atom` (but not very intuitive), special atom creator, or a helper function.

**Comment by dwelle** [comment] 2020-09-13 08:49
> I removed it from the core because it's sometimes extra work, and it seems to me a hidden implication.

What do you mean by extra work and hidden implication?

I'd argue making setters of primitive and derived atoms is not easily justifiable and intuitive. Especially since consumers of atoms don't know whether it's a derived atom (and why should they). In one case they can do functional updates, and in the other they can't. Why?

**Comment by dwelle** [comment] 2020-09-13 08:55
Ok, I understand why --- the setter of the derived atom is basically a reducer, and as such you don't want to prescribe what the `update` value is (same as `useReducer`). So this is a pickle.

**Comment by dai-shi** [comment] 2020-09-13 08:55
The thing is your derived atoms don't always support function updates and sometimes causes unexpected behavior.

For example, we can create a derived atom like this:
```js
const aaaAtom = atom(
  get => get(bbbAtom),
  (get, set, update) => set(cccAtom, update(get(dddAtom))),
)
```

If we implicitly do the function update like primitive atoms, it doesn't work as expected.

**Comment by dwelle** [comment] 2020-09-13 08:57
Yea, trouble is, since there's only a single `useAtom` API, users (especially non-TS users) can't easily know what type of atom they're using and what API to expect.

**Comment by dai-shi** [comment] 2020-09-13 09:16
Yeah, for non-TS usage, we'd need to make the atom name descriptive, for example.
Closing this as resolved.

**Closed by dai-shi** 2020-09-13 09:16 UTC
